REM execute one from FicherosEntrada folder and move results to Salidas\datetime
rem execute.bat codigo_xx.js %DATE%AT%TIME%
REM off
REM bucle de varias pruebas
REM siempre se ejecuta todo desde la carpeta Scripts
ECHO ............................................................................
echo INICIO DEL PROGRAMA EXECUTE ONE AND MOVE RESULTS TO ITS DESTINATION FOLDER
ECHO ............................................................................
CALL ..\Scripts\clean.bat
set i=%1
set folder=%2
ECHO OFF
ECHO .				...........................................................................
ECHO  				                          COPIANDO ARCHIVO %i%
ECHO .				...........................................................................
xcopy ..\FicherosEntrada\%i% ..\%i%*
ECHO .				...........................................................................
ECHO  				                          COPIA TERMINADA
ECHO .				...........................................................................
ECHO .				...........................................................................
ECHO  				                          EJECUTAR?
ECHO .				...........................................................................
pause
ECHO .				...........................................................................
ECHO  				                          EJECUCION ..\procesador.py ..\%i%
ECHO .				...........................................................................
python ..\procesador.py ..\%i%
ECHO .				...........................................................................
ECHO  				                          FIN DE EJECUCION
ECHO .				...........................................................................
ECHO .				...........................................................................
ECHO .				..........................MOVER ARCHIVOS DE SALIDA
ECHO .				...........................................................................
pause
ECHO .				...........................................................................
ECHO .				..........................MOVIENDO ARCHIVOS DE SALIDA
ECHO .				...........................................................................
echo move /-y .\fichero_errores.txt ..\Salidas\%folder%\fichero_errores_%i%.txt
move /-y .\fichero_errores.txt ..\Salidas\%folder%\fichero_errores_%i%.txt
move /-y .\fichero_parse.txt ..\Salidas\%folder%\fichero_parse_%i%.txt
move /-y .\fichero_tabla.txt ..\Salidas\%folder%\fichero_tabla_%i%.txt
move /-y .\fichero_tokens.txt ..\Salidas\%folder%\fichero_tokens_%i%.txt

ECHO .				...........................................................................
ECHO 						     			  FIN de parse para %i%
ECHO .				...........................................................................
pause

